name: Build and deploy Python project to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your function app project
  PYTHON_VERSION: '3.12'              # Specify supported Python version for Azure Functions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Optional: Install dependencies & run tests locally, but DO NOT deploy venv
      - name: Install dependencies (for unit tests only - not needed for deployment)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: Run tests here (do not package test results)
      # - name: Run tests
      #   run: pytest

      # Prepare zip for deployment, excluding any venv or __pycache__ folders
      - name: Archive for deployment
        run: |
          zip -r release.zip . -x "venv/*" "__pycache__/*" "*.pyc"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip for deployment
        run: |
          unzip release.zip
          rm release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: '<YourFunctionAppName>'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

